name: discord-bot
services:
  dice-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dice-bot
    entrypoint: ["python", "-u", "main_discord_bot.py"]
    volumes:
      - .:/code

